name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: set pub version
        run: |
          jq '.name |= $RELEASE_VERSION' package.json > _package.json
          mv _package.json package.json
      - name: Test
        run: |
          cat package.json
#      - run: yarn
#      - run: yarn publish // for Yarn version 1, use `yarn publish` instead
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
