name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'

      - name: Set env
        run: |
          cd node
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: set pub version
        run: |
          jq '.version |= "${{ env.RELEASE_VERSION }}"' package.json > _package.json
          mv _package.json package.json

      - name: Test
        run: |
          cat package.json

      - name: yarn install
        run: yarn

      - name: yarn build
        run: yarn build

      - name: yarn publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: create client
        run: ./make_client.sh

      - name: yarn publish client
        run: cd client && yarn build && yarn publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

